### ISSUE TITLE
Usage for creating runnable libs

### ISSUE THREAD

**Issue by slok** [brigadecore/brigadier#1]
Hi! 

First of all, thank you for all the work you've done with Brigade.

At this moment we are testing this library to remove a hack from our workers that gives us the ability to create a custom library with lot's of helpers that different teams use them on their/our pipelines.

I've started porting our lib to use npm, everything works until the worker runs, it doesn't do anything (our library creates Jobs). I know that the Readme says that the Job is dummy, so this was an expected behaviour. The thing is that I don't understand how I could use this library to create custom libraries for Brigade.

Could be possible the library have the [real k8s implementation](https://github.com/Azure/brigade/tree/master/brigade-worker/src) of the Job and only load this implementation when is on the worker? using a env var, importing other packages, dependency injection... so depending on what are you using the library for, you will create jobs from a Dummy class or real K8s implementation Job.

This way we could use it locally and also create libraries that create runnable jobs.

Does this make sense?

**Comment by radu-matei** [comment]
That is certainly an interesting idea, and honestly I don't see major downsides to this approach. 

We would split the worker implementation a bit, but we could then have a single place for the interface, actual Kubernetes implementation, mock implementation, and tests for this.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
