### ISSUE TITLE
export BrigadeEvent, BrigadeProject

### ISSUE THREAD

**Issue by jeffrom** [brigadecore/brigadier#37]
Hello, thanks for the great work on brigade.

At my company, we have a test suite we're currently porting over from Jenkins to brigade. In jenkins we have a helper library that packages several tests as helper functions. We'd like to do something similar in brigade, but we're hitting a snag where we need to pass around the BrigadeEvent and BrigadeProject types, but can't, because they aren't exported by brigadier (we have a typescript library using brigadier and brigade-utils and providing some higher-level functionality).

Currently the situation I have is, I'm working on a Job wrapper that can do retries, basically doing what's discussed over in https://github.com/brigadecore/brigade/issues/369#issuecomment-492684573. I've already copied Result, and a subset of BrigadeEvent and BrigadeProject. But now I want to run each attempt as a separate Check, and it looks like I'll need to copy the types completely in order to proceed.

Mostly looking for guidance: Am I barking up the wrong tree here? Would it be reasonable for brigadier to export these types? Is there a better approach?

Thanks again!

**Comment by krancour** [comment]
@jeffrom I'm slightly confused, because the types you've mentioned _are_ exported.

**Comment by jeffrom** [comment]
@krancour yep, you are right. I was mistakenly trying the import path `@brigadecore/brigadier/events`, the correct path is `@brigadecore/brigadier/out/events` 🤦‍♂️

thanks for the quick reply!
