### ISSUE TITLE
Migrate brigadier to the new Brigade org

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigadier#7]
As we're putting together the new organization for Brigade (see https://github.com/brigadecore), this repo would have to move there.

Other than updating the [relevant fields in `package.json`](https://github.com/Azure/brigadier/blob/master/package.json#L9-L11), is there anything related to the publishing of the NPM package that would be affected by the migration to the new org?
(As I think we currently publish the package manually, I would think there isn't, but better to be sure.)

**Comment by vdice** [comment]
This looks to have been completed!  Closing.
